[tool.poetry]
name = "hydrocronapi"
version = "1.0.0a5"
description = "OpenAPI access to Time Series data for SWOT features"
authors = ["PO.DAAC <podaac@jpl.nasa.gov>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/podaac/hydrocron-api"
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules"
]
exclude = ['contrib', 'docs', 'tests']

packages = [
    { include = "hydrocronapi" },
]

[tool.poetry.dependencies]
python = "^3.10"
six = "^1.16.0"
boto3 = "^1.28.18"
pandas = "^2.0.3"
shapely = "^2.0.1"
connexion = {version = "^2.14.2", extras = ["swagger-ui"]}
cryptography = "^41.0.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
flask-testing = "^0.8.1"
pylint = "^2.4"
flake8 = "^3.7"
pytest-cov = "~4"

[tool.poetry.scripts]
hydrocronapi = "hydrocronapi.__main__:__main__"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
